from tkinter import *
top = Tk()
scrollbar = Scrollbar(top)
scrollbar.pack(side=RIGHT, fill=Y)
Lb = Listbox(top)
Lb.insert(1, 'Python')
Lb.insert(2, 'Java')
Lb.insert( 22, "css")
Lb.insert(3, 'C++' , 2 ,"RRRRR")
Lb.insert(4, 'Any other')
Lb.pack()
top.mainloop()